name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '00 04 * * *'
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  vyos_url: https://github.com/vyos/vyos-build
  vyos_arch: amd64
  vyos_version: 1.5-rolling
  vyos_branch: current
  vyos_build_type: release
  vyos_build_by: "Michael Edelman"


jobs:
    build:
      runs-on: ubuntu-latest
  
      permissions:
        contents: write
  
      container:
        image: "vyos/vyos-build:current"
        options: --privileged
  
      steps:
        - name: Setup variables
          id: vars
          run: |
            build_date=$(date +%Y%m%d%H%M)
            echo "tag-name=${{ env.vyos_version }}-${build_date}" >> "$GITHUB_OUTPUT"
            echo "iso-name=${{ env.vyos_version }}-${build_date}-${{ env.vyos_arch }}" >> "$GITHUB_OUTPUT"

        - uses: actions/checkout@v4

        - name: Generate Version
          run: |
            if [[ ${{ startsWith(github.ref, 'refs/tags/') }} == 'true' ]]; then 
              echo "version=${{ github.ref_name }}" >>$GITHUB_ENV
            else
              echo "version=${{ env.vyos_version }}-dev-$(echo ${{ github.sha }} | cut -c 1-8)" >>$GITHUB_ENV
            fi
  
        - name: Executing scripts
          run: find scripts -name '*.sh' -exec bash {} \;
  
        - name: Clone Repository
          run: git clone -b ${{ env.vyos_branch }} --single-branch --depth 1 https://github.com/vyos/vyos-build.git

        - name: Download `sops` deb
          uses: robinraju/release-downloader@v1.8
          with:
            repository: mozilla/sops
            latest: true 
            fileName: "*amd64.deb"
            out-file-path: vyos-build/packages
              
        - name: Prepare custom packages
          run: |
            for deb in $(cat packages.txt); do
              mv ${deb} vyos-build/packages/
            done
  
        - name: Build ISO
          working-directory: vyos-build
          run: |
            sudo ./build-vyos-image iso \
                --architecture "${{ env.vyos_arch }}" \
                --build-by "${{ env.vyos_build_by }}" \
                --build-type "${{ env.vyos_build_type }}" \
                --version "${{ steps.vars.outputs.tag-name }}" \
                --build-comment "VyOS with additional packages" \
                --custom-package "git" \
                --custom-package "iptables" \
                --custom-package "jo" \
                --custom-package "jq" \
                --custom-package "moreutils" \
                --custom-package "python3-venv" \
                --custom-package "tree"
  
        - name: Rename ISO
          run: mv vyos-build/build/live-image-amd64.hybrid.iso vyos-${{ env.vyos_version }}.iso
  
        - uses: actions/upload-artifact@v3
          with:
            name: vyos-${{ env.vyos_version }}
            path: vyos-${{ env.vyos_version }}.iso
  
        - name: Checksums
          id: checksums
          run: |
            echo "md5sum=$(md5sum vyos-${{ env.vyos_version }}.iso | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
            echo "sha256sum=$(sha256sum vyos-${{ env.vyos_version }}.iso | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
            echo "sha512sum=$(sha512sum vyos-${{ env.vyos_version }}.iso | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
  
        - uses: crazy-max/ghaction-github-release@v2
          if: startsWith(github.ref, 'refs/tags/')
          with:
            files: vyos-${{ env.vyos_version }}.iso
            body: |
              | Digest | Checksum |
              |--------|----------|
              | md5    | `${{ steps.checksums.outputs.md5sum }}` |
              | sha256 | `${{ steps.checksums.outputs.sha256sum }}` |
              | sha512 | `${{ steps.checksums.outputs.sha512sum }}` |
            append_body: true
